# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ad694d30a3780bd946e89c83cd110656f3d1265c08e2e2005c03b819c6abb7758912ed5caa7ce7cde448a2d3d6dcb43cf16a7d862a4ea41c02f937083b6c019

test:
  secret_key_base: 1f7e292f51dd21b1956f453c8ce7af37c259a96646c506cced07c91c60bb817693ab1d025efa86351606b099b1c6ed5886d7f8134309e63209c9cae3bfda43ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
